### ISSUE TITLE
Replace synchronized locks with ReentrantLocks

### ISSUE THREAD

**Issue by slominskir** [JeffersonLab/epics2web#12]
We occasionally encounter situations where the server freezes.  Restarting the server is usually the fix.   The most innocent explanation perhaps is a starvation situation such that progress grinds to a halt due to overload.   It's also possible that there is a bug in our code or CAJ lib code that causes a deadlock situation - a thread holding a lock gets stuck.   One thing we could do to possibly make this situation better is to replace intrinsic locks obtained using `synchronized` with locks that have a timeout, such as a [ReentrantLock](https://docs.oracle.com/javase/6/docs/api/java/util/concurrent/locks/ReentrantLock.html).

Here is a report from Kay demonstrating the issue:

Log shows:
```
WARNING: Failed to send message to /x.x.x.x:5064 - buffer full, will retry.
```

JVM stack trace shows many threads stuck in “addPvs” like this:
```
"http-nio-8080-exec-32" #629188 daemon prio=5 os_prio=0 cpu=103256.22ms elapsed=672473.85s tid=0x00007f402e79a620 nid=0x54b5 waiting for monitor entry  [0x00007f4007bfc000]
java.lang.Thread.State: BLOCKED (on object monitor)
at org.jlab.epics2web.epics.ChannelManager.addPvs(ChannelManager.java:240)
- waiting to lock <0x00000006cc08b830> (a java.util.concurrent.ConcurrentHashMap)
at org.jlab.epics2web.websocket.WebSocketSessionManager.addPvs(WebSocketSessionManager.java:178)
at org.jlab.epics2web.websocket.MonitorEndpoint.onMessage(MonitorEndpoint.java:184)
at jdk.internal.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@15.0.1/DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(java.base@15.0.1/Method.java:564)
at org.apache.tomcat.websocket.pojo.PojoMessageHandlerWholeBase.onMessage(PojoMessageHandlerWholeBase.java:80)
at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:406)
at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:507)
at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:302)
at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:131)
at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:67)
- locked <0x00000007201c92c0> (a java.lang.Object)
at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler$WsReadListener.onDataAvailable(WsHttpUpgradeHandler.java:204)
at org.apache.coyote.http11.upgrade.AbstractServletInputStream.onDataAvailable(AbstractServletInputStream.java:203)
at org.apache.coyote.http11.upgrade.AbstractProcessor.upgradeDispatch(AbstractProcessor.java:93)
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:635)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1770)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1729)
- locked <0x00000006c0fecdd0> (a org.apache.tomcat.util.net.NioChannel)
at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@15.0.1/ThreadPoolExecutor.java:1130)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@15.0.1/ThreadPoolExecutor.java:630)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(java.base@15.0.1/Thread.java:832)
```
 
A single thread was in what looks like the opposite, “removeFromChannels”:
```
"http-nio-8080-exec-36" #629193 daemon prio=5 os_prio=0 cpu=111568.22ms elapsed=672468.90s tid=0x00007f4015423420 nid=0x54cf waiting for monitor entry  [0x00007f401acf0000]
java.lang.Thread.State: BLOCKED (on object monitor)
at org.jlab.epics2web.epics.ChannelManager.removeFromChannels(ChannelManager.java:338)
- waiting to lock <0x00000006cc08b830> (a java.util.concurrent.ConcurrentHashMap)
at org.jlab.epics2web.epics.ChannelManager.removeListener(ChannelManager.java:372)
at org.jlab.epics2web.websocket.WebSocketSessionManager.removeClient(WebSocketSessionManager.java:165)
at org.jlab.epics2web.websocket.MonitorEndpoint.onClose(MonitorEndpoint.java:132)
at jdk.internal.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@15.0.1/DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(java.base@15.0.1/Method.java:564)
at org.apache.tomcat.websocket.pojo.PojoEndpointBase.onClose(PojoEndpointBase.java:107)
at org.apache.tomcat.websocket.WsSession.fireEndpointOnClose(WsSession.java:515)
at org.apache.tomcat.websocket.WsSession.onClose(WsSession.java:496)
- locked <0x00000006c825da20> (a java.lang.Object)
at org.apache.tomcat.websocket.WsFrameBase.processDataControl(WsFrameBase.java:355)
at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:297)
at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:131)
at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:67)
- locked <0x00000006c825d7a0> (a java.lang.Object)
at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler$WsReadListener.onDataAvailable(WsHttpUpgradeHandler.java:204)
at org.apache.coyote.http11.upgrade.AbstractServletInputStream.onDataAvailable(AbstractServletInputStream.java:203)
at org.apache.coyote.http11.upgrade.AbstractProcessor.upgradeDispatch(AbstractProcessor.java:93)
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:635)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1770)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1729)
- locked <0x00000006c825b368> (a org.apache.tomcat.util.net.NioChannel)
at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@15.0.1/ThreadPoolExecutor.java:1130)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@15.0.1/ThreadPoolExecutor.java:630)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(java.base@15.0.1/Thread.java:832)
```
 

In this case these locks would likely benefit from a timeout:
- https://github.com/JeffersonLab/epics2web/blob/134f764d529b23a02c1717f532824c1ae70b91a1/src/main/java/org/jlab/epics2web/epics/ChannelManager.java#L240
- https://github.com/JeffersonLab/epics2web/blob/134f764d529b23a02c1717f532824c1ae70b91a1/src/main/java/org/jlab/epics2web/epics/ChannelManager.java#L338

**Comment by slominskir** [comment]
Worth mentioning this would not be a true fix, but just possibly an improvement as it would be trading freezes/lock-ups for resource leaks.   However, extra logging during these events may expose a pattern over time leading to an improved solution.   Retries could be used to minimize resource leaks.   Nightly restarts also minimize leaks.   Longer timeout on returning resources vs shorter timeout on creating resources may also minimize leaks.
