### ISSUE TITLE
JCA CAException: "Failed to obtain synchronization lock"

### ISSUE THREAD

**Issue by slominskir** [JeffersonLab/epics2web#2]
Users reported a PV which was not updating.   A restart of the epics2web fixed the issue.  Upon inspection of the log file it appears the JCA library threw an exception while attempting to close a channel and might have left the com.cosylab.epics.caj.impl.sync.NamedLockPattern, com.cosylab.epics.caj.impl.sync.ReferenceCountingLock, or something else in an odd state.  The stack trace is:

```
java.io.IOException: Unable to close channel
        at org.jlab.epics2web.epics.ChannelMonitor.close(ChannelMonitor.java:126)
        at org.jlab.epics2web.epics.ChannelManager.removeFromChannels(ChannelManager.java:333)
        at org.jlab.epics2web.epics.ChannelManager.removeListener(ChannelManager.java:353)
        at org.jlab.epics2web.websocket.WebSocketSessionManager.removeClient(WebSocketSessionManager.java:169)
        at org.jlab.epics2web.Application$1.run(Application.java:86)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: gov.aps.jca.CAException: Failed to obtain synchronization lock for 'R011PROT.F', possible deadlock.
        at com.cosylab.epics.caj.CAJContext.destroyChannel(CAJContext.java:1017)
        at com.cosylab.epics.caj.CAJChannel.destroy(CAJChannel.java:379)
        at com.cosylab.epics.caj.CAJChannel.destroy(CAJChannel.java:366)
        at org.jlab.epics2web.epics.ChannelMonitor.close(ChannelMonitor.java:124)
        ... 9 more
```

Note: we need to determine if problem is recoverable and if so, the generic CAException should ideally be replaced with a specific one such as something like "LockTimeoutException".   Upon inspection of the source code for CAJ, it appears lock acquisition is hard-coded to 20 seconds, after which the generic CAException is generated.   It is possible very high load results in slow lock acquisition, and that I could catch this Exception and use string pattern matching to search for something like the phrase "Failed to obtain synchronization lock" and then try the close operation again automatically to ensure internal bookkeeping is correctly done.   Or it is possible there really is an internal deadlock, in which case CAJ/JCA library needs to be fixed.

**Comment by slominskir** [comment]
Looks like this is due to a lock ordering issue in the CAJ/JCA library:

https://epics.anl.gov/tech-talk/2019/msg00050.php

I've implemented the workaround and will keep an eye out for future problems.

Fixed in Release 1.8.4 https://github.com/JeffersonLab/epics2web/releases/tag/v1.8.4
