### ISSUE TITLE
Over time channels are lost and do not recover

### ISSUE THREAD

**Issue by slominskir** [JeffersonLab/epics2web#6]
After running for an extended period of time channels become unavailable.   Other channels continue to work fine.  It appears this is due to errors closing the channel (Channels are opened and closed as web browser clients that request the channels come and go).  Specifically, failing to close a channel leaves epics2web in a bad state such that the given channel can no longer be used.  It is also possible Virtual Circuit Exceptions (code 60 Unresponsive) contribute to this problem as well, though that isn't clear.  The only "fix" at this time is to reboot the server.  The error closing the channel has been reported before and was thought to be addressed in https://github.com/JeffersonLab/epics2web/issues/2 (we are seeing the same Exception despite the fix).   

I see three possibilities:
   1. The CAJ API is not being used correctly by epics2web.   I assume that the internal locking should work regardless if I am calling createChannel and destroyChannel methods concurrently from multiple threads, but the documentation for the CAJ API is limited (and the internals are mostly a black box).  It is also possible I have lock ordering issues in epics2web itself (treating CAJ calls as another lock).
   1. There is still a bug in CAJ, even after https://github.com/JeffersonLab/epics2web/issues/2.
   1. The server is so overloaded that waiting on locks occasionally result in timeout.

Identifying which one is the root cause is tricky.   It is also temping to build in a reset that destroys the context and starts over.   That might work, but it is also tricky to stop a bunch of running threads (you have to ask politely, wait around, etc.   and this is complicated by the fact that the destroyChannel action itself is buggered so you may end up triggering the 20 second timeout on 1000s of channels! as closing a context destroys the channels - it might not be possible at all as internally the destroyChannel Exceptions might get bubbled up destroying the context).   We investigated this strategy in https://github.com/JeffersonLab/epics2web/issues/3, but concluded that it was the wrong response to a Virtual Circuit Exception as those exceptions should clean up themselves (API should handle reconnect).  It might be the correct response to a failure to close a channel though as that does not clean up itself and results in unavailable channels.

**Comment by slominskir** [comment]
After poking around in the CAJ code and reading some [training](https://epics.anl.gov/meetings/2009-07/talks/em_ChannelAccessClientProgramming.ppt) on EPICS CA Programming it looks like the API callbacks are not re-entrant.  In particular the class [gov.aps.jca.event.DirectEventDispatcher](https://github.com/epics-base/jca/blob/master/src/core/gov/aps/jca/event/DirectEventDispatcher.java) indicates that callbacks cannot call back into the CAJ Library directly.  I've updated callbacks to execute in separate threads.

**Comment by slominskir** [comment]
Still seeing Close Exceptions.

It looks like the close stacktrace is coming from close triggered in client (session) write thread not callback thread.

`at org.jlab.epics2web.Application$1.run(Application.java:77)`

Interesting that caget calls on "bugged" channel shows channel not connected.  Internal accounting buggered I guess:

```
java.lang.IllegalStateException: Channel not connected.
        at com.cosylab.epics.caj.CAJChannel.connectionRequiredCheck(CAJChannel.java:1086)
        at com.cosylab.epics.caj.CAJChannel.get(CAJChannel.java:900)
        at gov.aps.jca.Channel.get(Channel.java:538)
        at org.jlab.epics2web.epics.ChannelManager.doGet(ChannelManager.java:172)

```

I think other areas to investigate are usages of the channel specific namedLock.  Looks like it is used in two places: 

1. CAJContext.createChannel
2. CAJContext.destroyChannel

In the first case, it is interesting to note that if a channel is created while another user is creating a channel an alternate code path is executed in which CAJChannel.addConnectionListenerAndFireIfConnected() is called while holding the namedLock.  This results in callbacks being called while holding the lock.   Not great, but I guess they did warn you that callbacks are not re-entrant.   Might be worth fixing this?


There is another separate namedLock used for addreses (not PV names).  It is used in CAConnector.connect().  It is interesting because the Reactor.register() method is called and it uses Object.wait() while holding the namedLock.   If I am understanding correctly, I believe this is really bad as wait only releases "this" objects locks and waiting while holding locks is generally asking for trouble.  It might be the case that there is a relationship with these locks (trying to close a channel while others are trying to create it).

**Comment by slominskir** [comment]
Call SearchResponse.internalHandleResponse()
Call CAJContext.searchResponse()
Acquire lock CAJChannel object
Call CAJContext.getTransport()
Call CAConnector.connect()
Acquire lock namedLock (by IP Address)
Call Reactor.register()
Acquire lock RegistrationRequest object
Call RegistrationRequest.wait();

**Comment by slominskir** [comment]
Third time is the charm.  Or 4th time?   Anyways, it looks like I forgot to apply fix https://github.com/JeffersonLab/epics2web/issues/2 to the "caget" endpoint.   That could explain a deadlock and also could explain the " Channel not connected." too as the monitor side of the app was forcefully closing channels, which isn't very considerate of the caget side of the app.

See https://github.com/JeffersonLab/epics2web/releases/tag/v1.9.1

**Comment by slominskir** [comment]
Still seeing Exception.   

CAJContext.destroyChannel() may actually be called twice whenever a session closes.   The ordering is unpredictable, but both the session specific write thread (run() method) and the WebSocket API onClose() method call shutdown/destroy methods on the CA resources.   Also, looking into the ReentrantLock API that is used by CAJ, it appears lock acquisition it is interrupt-able.   Given that the onClose() method interrupts the write thread (run) in order to kill it then it means that the write thread may be in the middle of lock acquisition and would explain acquisition failure (not a deadlock, not an overload, but a third possibility - interruption).  If this is the case, then the close Exception can be safely ignored as it is caught and logged and cleanup is allowed to continue.

**Comment by slominskir** [comment]
We use a nightly Tomcat restart to clear any hung PVs.   Best theory is odd interaction of CA Gateway and CAJ on Channel Exception (IOC Reboot) causes odd hung state.
